#!/bin/bash
### BEGIN INIT INFO
# Provides:          dmg-torctl
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Digital output controler sysv init script
# Description:       Digital output controler
### END INIT INFO
# Version: 0.1.0
###############################################################################
# Copyright © 2016 epsilonRT, All rights reserved.                            #
# This software is governed by the CeCILL license <http://www.cecill.info>    #
###############################################################################

NAME=dmg-torctl
CONFIGFILE=/etc/$NAME.conf
DAEMON=/usr/local/bin/$NAME

XPL_IF=
XPL_DEBUG=
XPL_NET=

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

niceness=0
pgm_args="--quiet"

trim () {
  local var="$*"
  var="${var#"${var%%[![:space:]]*}"}"   # remove leading whitespace characters
  var="${var%"${var##*[![:space:]]}"}"   # remove trailing whitespace characters
  echo -n "$var"
}

set_args () {
  
  local tmpf=$(tempfile)
  # remove comments
  sed '/^[[:space:]]*\#/d' $CONFIGFILE > $tmpf
  
  local var=$(trim "$(grep 'iface' $tmpf | cut -d '=' -f2)")
  if [ "_$var" != "_" ]; then
    ifconfig $var > /dev/null 2>&1 && XPL_IF=$var
  fi
  if [ "_$XPL_IF" != "_" ]; then
    XPL_IF="-i $XPL_IF"
  fi
  
  var=$(trim "$(grep 'net' $tmpf | cut -d '=' -f2)")
  if [ "$var" = "udp" ] || [ "$var" = "xbeezb" ]; then
    XPL_NET="-n $var"
  fi
  
  var=$(trim "$(grep 'debug' $tmpf | cut -d '=' -f2)")
  if [ "$var" = "1" ] || [ "$var" = "true" ]; then
    XPL_DEBUG=-ddd
  fi

  rm -f $tmpf
}

daemon_start () {

  set_args
  log_daemon_msg "Starting Digital output controler" "dmg-torctl"
  start-stop-daemon --start $pgm_args --oknodo --nicelevel $niceness --exec $DAEMON -- $XPL_IF $XPL_NET $XPL_DEBUG
  log_end_msg $?
  return $?
}

daemon_stop () {
  
  log_daemon_msg "Stopping Digital output controler" "dmg-torctl"
  start-stop-daemon --stop  $pgm_args --retry 5 --exec $DAEMON
  log_end_msg $?
  return $?
}


case "$1" in
  start)
    daemon_start
    ;;
  stop)
    daemon_stop
    ;;
  force-reload|restart)
    daemon_stop
    daemon_start
    ;;
  status)
    status_of_proc $DAEMON "Digital output controler" && exit 0 || exit $?
    ;;
  *)
     echo "Usage: /etc/init.d/dmg-torctl {start|stop|restart|force-reload|status}"
     exit 1
esac

exit 0
